---
# -----------------------------------------------------------------------------
# dCloud ISE Sandbox Hosts
#
# For details on creating Ansible inventory files, see
# https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html
# For common patterns for targeting inventory hosts and groups:
# https://docs.ansible.com/ansible/latest/user_guide/intro_patterns.html
# Verify inventory with
#   ansible-inventory -i inventory --graph
#   ansible-inventory -i inventory --host <hostname>
#   ansible-inventory -i inventory --list
# -----------------------------------------------------------------------------

# ungrouped: a default group containing hosts not in group 'all'
# Variable precedence: all < parent group < child group < host

all:
  vars:
    # no global vars
  hosts:
    localhost:
      ansible_connection: local # do not use SSH by default
  children:
    ise_nodes:
      hosts:
        ise:
          ansible_host: 172.31.2.11 # ⭐ Change me to your ISE node's IP address!
        # ▼ You can add more ISE nodes here ▼
        # ise-2:
        #   ansible_host: 172.31.2.12 # ⭐ Change me to your ISE node's IP address!
      vars: # these group_vars are shared among the ISE nodes
        ansible_become: no # ISE does not have a superuser/enable mode
        ansible_connection: ansible.netcommon.network_cli
        ansible_network_os: cisco.ios.ios
        # ⭐ ISE SSH username is `iseadmin` for ISE 3.2+ cloud instances!
        ansible_ssh_user:     "{{ lookup('env','ISE_SSH_USERNAME') }}"
        # ⭐ Un/Comment the SSH password or private_key_file - whichever you use!
        ansible_ssh_password: "{{ lookup('env','ISE_SSH_PASSWORD') }}"
        # ansible_ssh_private_key_file: ~/.ssh/id_rsa
