---
- name: Show ISE Configuration
  hosts: ise
  gather_facts: no
  vars_prompt:
    - name: username
      prompt: What is the username to reset?
      default: admin
      private: no
    - name: new_password
      prompt: What is the new password?
      private: yes
  tasks:

    #--------------------------------------------------------------------------
    # 💡 ISE 3.2+ cloud instances use the superadmin account `iseadmin`
    #
    # 💡 ISE Application Server must be running to reset password!
    #
    # 💡 Possible errors:
    #    - Cannot reuse password within {{n}} days.
    # Example command output:
    #
    # ```
    # ise/admin#application reset-passwd ise admin
    # Enter new password:
    # Confirm new password:
    #
    # Password reset successfully.
    # ```
    #--------------------------------------------------------------------------

    - name: Password Reset | {{ username }}@{{ inventory_hostname }}
      ansible.netcommon.cli_command:
        command: "application reset-passwd ise {{ username }}"
        check_all: yes
        sendonly: no
        newline: yes
        prompt:
          - "Enter new password:"
          - "Confirm new password:"
        answer:
          - "{{ new_password }}\r"
          - "{{ new_password }}\r"
      register: output
      failed_when: "'successfully' not in output.stdout"

    - name: Exit | {{ inventory_hostname }}
      when: username == "admin"
      ansible.netcommon.cli_command:
        command: "exit"
