---
- name: ISE reload
  hosts: ise
  gather_facts: no
  tasks:

    #--------------------------------------------------------------------------
    # Example command output:
    #
    # ise/admin#reload
    # Save the current ADE-OS running configuration? (yes/no) [yes] ? yes
    # Generating configuration...
    # Saved the ADE-OS running configuration to startup successfully
    #
    # Broadcast message from root@ise (pts/1) (Sun Oct  9 15:14:28 2022):
    #
    # Trying to stop processes gracefully. Reload might take approximately 3 mins
    #--------------------------------------------------------------------------

    - name: reload | {{ inventory_hostname }}
      vars:
        #  ⚠ ISE 3.2: A command timeout of < ~7 minutes will cause a failure!
        ansible_command_timeout: 600
      ansible.netcommon.cli_command:
        command: reload
        check_all: yes # run all of the commands
        prompt:
          # Save the current ADE-OS running configuration? (yes/no) [yes] ?
          - Save the current ADE-OS running configuration
          # Continue with reboot? [y/n]
          - Continue with reboot
          # Trying to stop processes gracefully. Reload might take approximately 3 mins
        answer:
          - "yes"
          - "y"
      register: output
      failed_when: "'gracefully' not in output.stdout"


...