---
- name: Show ISE Configuration
  hosts: ise
  gather_facts: no
  tasks:
    - name: ISE CLI | show running-config
      ansible.netcommon.cli_command:
        command: show running-config
      register: output

    - name: Show output
      ansible.builtin.debug:
        msg: "{{ output.stdout | replace('\n\n','\n') }}" # remove empty lines
